// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    LeagueSelector: typeof import("./components/LeagueSelector.vue")["default"];
    MonFilterOptions: typeof import("./components/MonFilterOptions.vue")["default"];
    MonRenderer: typeof import("./components/MonRenderer.vue")["default"];
    MonTable: typeof import("./components/MonTable.vue")["default"];
    NavBar: typeof import("./components/NavBar.vue")["default"];
    ProgressBar: typeof import("./components/ProgressBar.vue")["default"];
    SearchUI: typeof import("./components/SearchUI.vue")["default"];
    TeamRenderer: typeof import("./components/TeamRenderer.vue")["default"];
  }
}

export {};
